<?php
namespace GenyBundle\Repository;

/**
 * DataTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class DataTextRepository extends \Doctrine\ORM\EntityRepository
{  
}